#!/usr/bin/env python3
"""
Cosine similarity fidelity test for HF vs GGUF embedding models.

Compares embeddings generated by the original HuggingFace model against
embeddings generated by the converted BF16 GGUF model for the same input
sentences. Logs cosine similarity scores per sentence so the user can assess
how much information was preserved during HF -> GGUF conversion.

This script does not pass or fail — it is purely informational output.

Usage:
  python test_embedding_cosine_hf_gguf.py <hf_model_path> <gguf_model_path> <llama_embedding_bin>
    [--sentences "sentence 1" "sentence 2" ...]

Examples:
  python test_embedding_cosine_hf_gguf.py \\
    models/ibm-granite/granite-embedding-small-english-r2 \\
    models/sanjanasrikanth/granite-embedding-small-english-r2-GGUF/granite-embedding-small-english-r2-bf16.gguf \\
    ./bin/b8100/llama-embedding
"""

import sys
import json
import argparse
import subprocess
import numpy as np
from pathlib import Path


def cosine_similarity(vector_a: np.ndarray, vector_b: np.ndarray) -> float:
    """Compute cosine similarity between two 1-D vectors."""
    vector_a = np.asarray(vector_a, dtype=np.float32)
    vector_b = np.asarray(vector_b, dtype=np.float32)
    numerator = np.dot(vector_a, vector_b)
    denominator_a = np.linalg.norm(vector_a)
    denominator_b = np.linalg.norm(vector_b)
    if denominator_a == 0 or denominator_b == 0:
        return 0.0
    cosine_sim = numerator / (denominator_a * denominator_b)
    return float(cosine_sim)


def generate_hf_embedding(sentence, model):
    """Generate a normalized 1-D embedding using SentenceTransformer."""
    # encode() returns shape (1, dim) when passed a list; take [0] for a 1-D vector
    embedding = model.encode([sentence])
    return embedding[0]  # shape: (dim,)


def generate_gguf_embedding(sentence, gguf_model_path, llama_embedding_bin):
    """
    Generate a normalized 1-D embedding from the GGUF model via llama-embedding.
    Uses --embd-output-format json for structured output and
    --embd-normalize 2 (L2 normalization) to match SentenceTransformer defaults.
    """
    cmd = [
        llama_embedding_bin,
        "-m", gguf_model_path,
        "-p", sentence,
        "--embd-output-format", "json",
        "--embd-normalize", "2",
    ]

    proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    if proc.returncode != 0:
        stderr = proc.stderr.decode("utf-8", errors="replace")
        raise RuntimeError(
            f"llama-embedding failed (exit {proc.returncode}):\n{stderr}"
        )

    stdout = proc.stdout.decode("utf-8", errors="replace")

    # Parse JSON from stdout — llama-embedding may mix log lines with JSON output
    start = stdout.find("{")
    if start == -1:
        raise ValueError(f"No JSON object found in llama-embedding output:\n{stdout}")

    try:
        data = json.loads(stdout[start:])
    except json.JSONDecodeError as e:
        raise ValueError(f"Failed to parse llama-embedding JSON output: {e}\n{stdout}")

    # Extract embedding array from OpenAI-compatible JSON structure:
    # {"object":"list","data":[{"object":"embedding","embedding":[...],"index":0}]}
    if "data" not in data or not data["data"]:
        raise ValueError(f"No 'data' field in llama-embedding output: {data}")

    embedding = data["data"][0].get("embedding")
    if embedding is None:
        raise ValueError(f"No 'embedding' field in llama-embedding data: {data['data'][0]}")

    return np.array(embedding, dtype=np.float32)


def main():
    parser = argparse.ArgumentParser(
        description="Cosine similarity fidelity test: HF model vs GGUF model embeddings.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("hf_model_path", help="Path to the HuggingFace model directory")
    parser.add_argument("gguf_model_path", help="Path to the BF16 GGUF model file")
    parser.add_argument("llama_embedding_bin", help="Path to the llama-embedding binary")
    parser.add_argument(
        "--sentences", nargs="+",
        default=[
            "Artificial intelligence was founded as an academic discipline in 1956.",
            "AI started as an academic field in the 1950s.",
            "Delicious pepperoni pizza with extra cheese and mushrooms makes my favorite weekend meal.",
        ],
        help="Test sentences to compare (default: 3 standard embedding test sentences)",
    )

    args = parser.parse_args()

    print("[INFO] ==========================================")
    print("[INFO] HF vs GGUF Cosine Similarity Fidelity Test")
    print("[INFO] ==========================================")
    print(f"[INFO] HF model:           {args.hf_model_path}")
    print(f"[INFO] GGUF model:         {args.gguf_model_path}")
    print(f"[INFO] llama-embedding:    {args.llama_embedding_bin}")
    print(f"[INFO] Sentences:          {len(args.sentences)}")
    print("[INFO] ==========================================")
    print()

    try:
        from sentence_transformers import SentenceTransformer
    except ImportError:
        print("[ERROR] sentence_transformers is not installed.")
        print("[ERROR] Install with: pip install sentence_transformers")
        sys.exit(1)

    print(f"[INFO] Loading HF model from: {args.hf_model_path}")
    model = SentenceTransformer(args.hf_model_path)
    print("[INFO] HF model loaded successfully")
    print()

    similarities = []

    for i, sentence in enumerate(args.sentences, 1):
        print(f"[INFO] --- Sentence {i} ---")
        print(f"[INFO] Text: {sentence}")

        print("### BASELINE (HF) ###")
        hf_emb = generate_hf_embedding(sentence, model)
        print("Embedding shape:", hf_emb.shape)
        print("Embedding vector:", hf_emb[:8])

        print("### llama.cpp (GGUF) ###")
        gguf_emb = generate_gguf_embedding(sentence, args.gguf_model_path, args.llama_embedding_bin)
        print("Embedding shape:", gguf_emb.shape)
        print("Embedding vector:", gguf_emb[:8])

        print()
        sim = cosine_similarity(hf_emb, gguf_emb)
        similarities.append(sim)
        print(f"COSINE SIMILARITY: {sim:.6f}")
        print("--------------------------------")
        print()

    print("[INFO] ==========================================")
    print("[INFO] Summary")
    print("[INFO] ==========================================")
    for i, (sentence, sim) in enumerate(zip(args.sentences, similarities), 1):
        print(f"  Sentence {i}: {sim:.6f}  |  {sentence[:60]}")
    print(f"  Average:    {float(np.mean(similarities)):.6f}")
    print(f"  Min:        {float(np.min(similarities)):.6f}")
    print(f"  Max:        {float(np.max(similarities)):.6f}")
    print("[INFO] ==========================================")
    print("[INFO] Test complete — results are informational only")

    sys.exit(0)


if __name__ == "__main__":
    main()
