# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

#on:
#  release:
#    types: [created]
#  workflow_dispatch:

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  LLAMACPP_DIR: llama.cpp
  MODEL_DOWNLOAD_DIR: models
  FIND_ARGS: "-not -path '*/.*' -print | sed -e 's;[^/]*/;|___;g;s;___|; |;g'"

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        repo_id: ["ibm-granite/granite-3.0-2b-instruct"]
        quantization: ["Q4_0","Q4_K_M"]

    steps:
    - uses: actions/checkout@v4
    - name: confirm-os-arch
      run: |
        uname -a
        echo "Operating System: ${{ runner.os }}"
        echo "Architecture: ${{ runner.arch }}"
        echo "repo_id: ${{ matrix.repo_id }}"    
        echo "quantization: ${{ matrix.quantization }}"              

    # alias tree="find . -print | sed -e 's;[^/]*/;|___;g;s;___|; |;g'"    
    # To allow `alias` in the default, non-interactive shell override using `shopt`.
    - name: create-aliases
      if: runner.os == 'macOS'
      run: |
        shopt -s expand_aliases
        alias tree="find"

    # - name: install-linux-commands
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y tree

    # Note: at the current time, we cannot use Python versions > 3.11 due to HF and langchain deps.
    # Note: you can verify in a step using: run: python -c "import sys; print(sys.version)"
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Use this step to set values to the github context (shared across jobs/steps)
    - name: set-github-env
      id: github_env
      run: |
        echo "full_path=models/ibm-granite/foo" >> $GITHUB_OUTPUT
        echo "working_dir='$PWD'" >> $GITHUB_OUTPUT

    - name: verify-github-env
      run: |   
        echo "working_dir=${{ steps.github_env.outputs.working_dir }}"      
        echo "full_path=${{ steps.github_env.outputs.full_path }}"

    # for GGUF conversion, we only need a shallow copy (depth=1) and
    # specify only the scripts and requirements files we need (sparse).
    # Note: we include LICENSE for future BOM generation
    - name: shallow-clone-llamacpp
      uses: actions/checkout@v4
      with:
        path: ${{ env.LLAMACPP_DIR }} # checkout under this directory
        repository: 'ggerganov/llama.cpp'
        ref: 'master'  # default to master branch
        fetch-depth: 1
        sparse-checkout-cone-mode: false
        sparse-checkout: |
          LICENSE
          convert_hf_to_gguf.py
          convert_lora_to_gguf.py
          requirements/requirements-convert_legacy_llama.txt
          requirements/requirements-convert_hf_to_gguf.txt
          requirements/requirements-convert_lora_to_gguf.txt
          gguf-py
          scripts

    - name: print-llamacpp
      run: |
        echo "PATH: '{{$PATH}}'"
        ls -al llama.cpp
        find llama.cpp ${{env.FIND_ARGS}}
 
    - name: install-dependencies
      run: |
        python -m pip install -r ./requirements.txt
        python -m pip install -r ./llama.cpp/requirements/requirements-convert_hf_to_gguf.txt
        python -m pip install -r ./llama.cpp/requirements/requirements-convert_lora_to_gguf.txt
        pip list

    - name: download-model
      run: |
        echo "working_dir: '$(pwd)'"  
        echo "MODEL_DOWNLOAD_DIR: ${{env.MODEL_DOWNLOAD_DIR}}"
        echo "repo_id: ${{ matrix.repo_id }}"   
        echo "quantization: ${{ matrix.quantization }}"      
        "repo_id=${{ matrix.repo_id }}"   
        echo $repo_id                
        echo "download_dir='$MODEL_DOWNLOAD_DIR/$repo_id/'"    
        echo $download_dir        
        echo "output_dir='$MODEL_DOWNLOAD_DIR/${{ matrix.repo_id }}'"    
        echo $output_dir                              
        python ./scripts/download_model_from_hf.py $MODEL_DOWNLOAD_DIR ibm-granite granite-3.0-2b-instruct
        find models ${{env.FIND_ARGS}}
        exit 0

    - name: convert-hf-to-gguf
      run: |
        exit 0
        echo "MODEL_DOWNLOAD_DIR: ${{env.MODEL_DOWNLOAD_DIR}}"    
        echo "repo_id: ${{ matrix.repo_id }}"   
        echo "quantization: ${{ matrix.quantization }}"     
        echo "download_dir='$MODEL_DOWNLOAD_DIR/ibm-granite/granite-3.0-2b-instruct/'"
        ls -al models
        python ./llama.cpp/convert_hf_to_gguf.py $MODEL_DOWNLOAD_DIR/ibm-granite/granite-3.0-2b-instruct/ --outfile $MODEL_DOWNLOAD_DIR/ibm-granite/granite-3.0-2b-instruct/f16.gguf --verbose

    - name: quantize-gguf
      run: |
        echo "MODEL_DOWNLOAD_DIR: ${{env.MODEL_DOWNLOAD_DIR}}"    
        echo "repo_id: ${{ matrix.repo_id }}"   
        echo "quantization: ${{ matrix.quantization }}"   
        ./bin/llama-quantize $MODEL_DOWNLOAD_DIR/ibm-granite/granite-3.0-2b-instruct/ f16.gguf quantized.gguf ${{matrix.quantization}}
        ls -al *.gguf
