name: create-hf-repos-reusable

on:
  workflow_call:
    secrets:
      hf_token:
        required: true
      api_token:
        required: false
    inputs:
      enable_llm_jobs:
        type: boolean
        required: false
        default: false
      enable_guardian_jobs:
        type: boolean
        required: false
        default: false
      enable_embedding_jobs:
        type: boolean
        required: false
        default: false
      enable_vision_jobs:
        type: boolean
        required: false
        default: false
      granite_family:
        type: string
        required: true
      hf_collection_config:
        type: string
        required: true
      target_repo_owner:
        type: string
        required: true
      target_repo_name_ext:
        type: string
        required: true
      debug:
        type: boolean
        required: true
        default: false
      target_repo_private:
        type: boolean
        required: false
        default: true

jobs:
  reusable_create_hf_repos:
    runs-on: macos-latest
    if: ${{ inputs.enable_llm_jobs == true || inputs.enable_vision_jobs == true || inputs.enable_guardian_jobs == true || inputs.enable_embedding_jobs == true }}
    steps:
    - uses: actions/checkout@v4
    - run: |
        echo "[INFO] github.env:"
        echo "[INFO] >> run_id: '${{ github.run_id }}'"
        echo "[INFO] >> ref: '${{ github.ref }}', ref_name: '${{ github.ref_name }}', ref_type: '${{ github.ref_type }}'"
        echo "[INFO] >> workflow_ref: '${{ github.workflow_ref }}'"
        echo "[INFO] >> event_type: '${{ github.event_type }}'"
        echo "[INFO] >> event.: action: '${{ github.event.action }}'"
        echo "[INFO] >> event.: base_ref: '${{ github.event.base_ref }}'"
        echo "[INFO] >> event.: workflow_run.conclusion: '${{ github.event.workflow_run.conclusion }}'"
        echo "[INFO] >> event.release.: name: '${{ github.event.release.name }}', tag_name: '${{ github.event.release.tag_name }}'"

    # - name: Dump GitHub context
    #   env:
    #     GH_CONTEXT: ${{ toJson(github) }}
    #   run: echo "$GH_CONTEXT"

    # - name: Dump GitHub inputs
    #   env:
    #     GITHUB_INPUTS: ${{ toJson(inputs) }}
    #   run: echo "$GITHUB_INPUTS"

    # - name: Dump GitHub quiet
    #   env:
    #     GH_QUIET: ${{ toJson(secrets) }}
    #   run: echo "$GH_QUIET"

    # Note: at the current time, we cannot use Python versions > 3.11 due to HF and langchain deps.
    # Note: you can verify in a step using: run: python -c "import sys; print(sys.version)"
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # primarily huggingface_hub
    - name: install-dependencies
      run: |
        python -m pip install -r ./requirements.txt
        pip list

    - name: create-hf-repos
      run: |
        echo "inputs.target_repo_private: '${{ inputs.target_repo_private }}'"
        echo "inputs.target_repo_name_ext: '${{ inputs.target_repo_name_ext }}'"
        python ./scripts/hf_repos_create.py ${{ inputs.target_repo_owner }} ${{ inputs.hf_collection_config }} ${{ inputs.granite_family }} ${{ inputs.target_repo_private }} ${{ secrets.hf_token }} "--repo-ext GGUF"
