name: create-repo-reusable

on:
  workflow_call:
    inputs:
      hf_collection_config:
        required: true
        type: string
      target_repo_owner:
        required: true
        type: string
      var1:
        type: string   
        required: true        
        default: "default-value"
      var2:
        type: string
        required: true        
        default: "default-value"

jobs:   
  reusable_workflow_job:
    runs-on: macos-latest
    steps: 
    - run: |
        echo "[INFO] github.env:"   
        echo "[INFO] >> run_id: '${{ github.run_id }}'"       
        echo "[INFO] >> ref: '${{ github.ref }}', ref_name: '${{ github.ref_name }}', ref_type: '${{ github.ref_type }}'"
        echo "[INFO] >> workflow_ref: '${{ github.workflow_ref }}'"         
        echo "[INFO] >> event_type: '${{ github.event_type }}'" 
        echo "[INFO] >> event.: action: '${{ github.event.action }}'"
        echo "[INFO] >> event.: base_ref: '${{ github.event.base_ref }}'"          
        echo "[INFO] >> event.: workflow_run.conclusion: '${{ github.event.workflow_run.conclusion }}'"
        echo "[INFO] >> event.release.: name: '${{ github.event.release.name }}', tag_name: '${{ github.event.release.tag_name }}'"

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"   

    - name: Dump GitHub inputs
      env:
        GITHUB_INPUTS: ${{ toJson(inputs) }}
      run: echo "$GITHUB_INPUTS"   

    - name: Set branch name for tag
      run: |
        echo "REPO_BRANCH=$(git branch -r --contains ${{ github.ref }})" >> $GITHUB_ENV

    - name: Echo branch name for tag
      run: |        
        echo "[INFO] REPO_BRANCH: '${{ env.REPO_BRANCH }}'"