name: delete-cancelled-workflows

on:
  workflow_dispatch:
#   schedule:
#     - cron: '0 1 * * *' # every day at 01:00 UTC

jobs:
  delete_cancelled_runs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # https://api.github.com/repos/IBM/gguf/actions/runs
      - name: List workflow runs
        id: list_runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "github.repository: '${{ github.repository }}'"
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs" > workflow_runs.json
          cat workflow_runs.json

      - name: Filter cancelled runs
        id: filter_cancelled_runs
        run: |
          jq '.workflow_runs[] | select(.conclusion == "cancelled") | .id' workflow_runs.json > cancelled_runs.json
          echo "=== BEGIN: cancelled_runs.json ======="
          cat cancelled_runs.json
          echo "=== END: cancelled_runs.json ========"

      - name: Delete cancelled runs
        id: delete_cancelled_runs
      #   env:
      #     GH_TOKEN: ${{ github.token }}        
        run: |
          for line in $(cat "cancelled_runs.json"); do
            echo "$line"
          done          
        # export RUN_IDS=$(cat cancelled_runs.json | jq -r '.[] | .id')
        # echo "RUN_IDS: '$RUN_IDS'"
        # for run in $run_id; do
        #   curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        #     "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id"
        # done
